# This file was generated by GoReleaser. DO NOT EDIT.
cask "mark42" do
  version "3.4.1"

  on_macos do
    on_arm do
      sha256 "ff85afd6191e460fc08bba9c7c4362c3a113554ef98e356427dfba87dbfc2589"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c751d746f18dff2ce9c392a5ef1cce1eef717981869055cf7313ed6afe84925"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c16b4f4d2d326ac79c2dcb93390369f6b9c7b67c5f6abd14986ae1c6d9abd46c"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c6b5eebf4f5862febf1faafba1d3c60e11a575b5a19125a9c989ba4fdb2ddbc2"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mark42"
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mark42"
  binary "mark42-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mark42"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mark42-server"]
    end
  end

  # No zap stanza required
end
