# This file was generated by GoReleaser. DO NOT EDIT.
cask "mark42" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "mark42"], chdir: "."
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "mark42-server"], chdir: "."
    end
  end

  version "4.0.0"

  on_macos do
    on_arm do
      sha256 "aac028db2195b65348a5a8f75104ddf6e4ba171624c9b97696ac5c1122234378"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a4b06e3fb4da9fbe5e05b50ef87e7fd084c725f79067290504e952109b8914d"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf46ec3e00123fb1478344243fe4a9f63fe08572ad086931d2c32fd3de9c15aa"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02d95df19ca8d817af4bab30eb815b09baa362ded8f47aeafd49d77177be282a"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mark42"
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mark42"
  binary "mark42-server"

  # No zap stanza required
end
