# This file was generated by GoReleaser. DO NOT EDIT.
cask "mark42" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "mark42"], chdir: "."
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "mark42-server"], chdir: "."
    end
  end

  version "3.5.1"

  on_macos do
    on_arm do
      sha256 "f86f8c43112e095ca439fad2cda7fcdf0dccd522645e82039e4b309ada5ba69c"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d616a00da4dde87781d23194fc039ed81a959529e025e6b5c5163242fdbd7edd"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ceb66d6e85ceb24a4b074111b0c28bb6689fbd441bcd9ad7bcc02fa58d7d494b"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "80dd13bdd0648e5397ecfa4a2379a7b062f2cc0b13f206156860713cbd512092"
      url "https://github.com/mfenderov/mark42/releases/download/v#{version}/mark42_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mark42"
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mark42"
  binary "mark42-server"

  # No zap stanza required
end
