# This file was generated by GoReleaser. DO NOT EDIT.
cask "veronica" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "veronica"], chdir: "."
    end
  end

  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "8ed3ffc4c62c37d04df11de6886e6832bd5edfbaadf7a2bcbb5acbc3f692d21d"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "97391dbec5fd0e309fe08c25931141f5e35bd6519e54fb880ae08cadf6c56204"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9c167d3c3253eea8b91ca199464a7080ab0030f9f405de10355e246c7f87a21c"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "817e601576f7099ad5c253c73255a18cb823bb56cd4083d2bd15d09693b7c2be"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_amd64.tar.gz"
    end
  end

  name "veronica"
  desc "Autonomous local MCP gateway and dynamic tool pod"
  homepage "https://github.com/mfenderov/veronica"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "veronica"

  # No zap stanza required
end
