# This file was generated by GoReleaser. DO NOT EDIT.
cask "veronica" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "veronica"], chdir: "."
    end
  end

  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "61f90cb70cfcfb8229d228da0c9d2aa3b76bc9c5618f8ba1771370098362e82f"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "304fc8b5e17259098b6a480df4fc36c2ed00d462a80da19c41ec5e238e0e3339"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f0ee394441b654026d2832c9f2fbfacf7fa492be3c2bd39df6e26a386747068d"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e49c11a9a3c9c69574983ef5c5873a40fc5b78645f1505e7c1ff736e1b70be8"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_amd64.tar.gz"
    end
  end

  name "veronica"
  desc "Autonomous local MCP gateway and dynamic tool pod"
  homepage "https://github.com/mfenderov/veronica"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "veronica"

  # No zap stanza required
end
