# This file was generated by GoReleaser. DO NOT EDIT.
cask "veronica" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "veronica"], chdir: "."
    end
  end

  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "90692601709d50a08f9edd273910391047ffb76e9ce268bcb15781e9c197586e"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "04c753670e7389ee396cff0ed5a00379eb5f40a581f72e1d476672f9811152f6"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c9a3d77ae6c76db241a47d5fa217f6f46b05f626bfbedca05a2c396baff071a5"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "90647e7bac451082fb42a3d30011bec3ced1d44a3232749700e01b5d585d7988"
      url "https://github.com/mfenderov/veronica/releases/download/v#{version}/veronica_#{version}_linux_amd64.tar.gz"
    end
  end

  name "veronica"
  desc "Autonomous local MCP gateway and dynamic tool pod"
  homepage "https://github.com/mfenderov/veronica"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "veronica"

  # No zap stanza required
end
