# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeMemory < Formula
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/claude-memory"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfenderov/claude-memory/releases/download/v1.1.0/claude-memory_1.1.0_darwin_amd64.tar.gz"
      sha256 "28d2b5c24f6a70678e8298c2b79f7b8ad7923c3315a2ae2237209dcae7d798f3"

      def install
        bin.install "claude-memory"
        bin.install "claude-memory-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"claude-memory").install ".claude-plugin"
        (share/"claude-memory").install "agents"
        (share/"claude-memory").install "skills"
        (share/"claude-memory").install "commands"
        (share/"claude-memory").install "hooks"
        (share/"claude-memory").install "hooks.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfenderov/claude-memory/releases/download/v1.1.0/claude-memory_1.1.0_darwin_arm64.tar.gz"
      sha256 "9209f504e4d7c7e0018397af7b612af4e1dd17e79f312a1841df72d1d85c1247"

      def install
        bin.install "claude-memory"
        bin.install "claude-memory-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"claude-memory").install ".claude-plugin"
        (share/"claude-memory").install "agents"
        (share/"claude-memory").install "skills"
        (share/"claude-memory").install "commands"
        (share/"claude-memory").install "hooks"
        (share/"claude-memory").install "hooks.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/claude-memory/releases/download/v1.1.0/claude-memory_1.1.0_linux_amd64.tar.gz"
      sha256 "8805e01da29dc3c0d9c76b6219ba2d2f1b80aebd8d7fa93266f62ef7d1433ecc"
      def install
        bin.install "claude-memory"
        bin.install "claude-memory-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"claude-memory").install ".claude-plugin"
        (share/"claude-memory").install "agents"
        (share/"claude-memory").install "skills"
        (share/"claude-memory").install "commands"
        (share/"claude-memory").install "hooks"
        (share/"claude-memory").install "hooks.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/claude-memory/releases/download/v1.1.0/claude-memory_1.1.0_linux_arm64.tar.gz"
      sha256 "b6f3a45f19620aa1b5fcb96b1504df40654323570b41d5e841b5042c59d0f97e"
      def install
        bin.install "claude-memory"
        bin.install "claude-memory-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"claude-memory").install ".claude-plugin"
        (share/"claude-memory").install "agents"
        (share/"claude-memory").install "skills"
        (share/"claude-memory").install "commands"
        (share/"claude-memory").install "hooks"
        (share/"claude-memory").install "hooks.json"
      end
    end
  end

  def post_install
    # Create Claude Code plugin directory structure
    plugin_dir = Pathname.new(Dir.home) / ".claude" / "plugins" / "local" / "claude-memory"

    # Clean up existing installation (handles upgrades)
    plugin_dir.rmtree if plugin_dir.exist?
    plugin_dir.mkpath
    (plugin_dir / "bin").mkpath

    # Symlink plugin files from share directory
    ln_s share/"claude-memory"/".claude-plugin", plugin_dir/".claude-plugin"
    ln_s share/"claude-memory"/"agents", plugin_dir/"agents"
    ln_s share/"claude-memory"/"skills", plugin_dir/"skills"
    ln_s share/"claude-memory"/"commands", plugin_dir/"commands"
    ln_s share/"claude-memory"/"hooks", plugin_dir/"hooks"
    ln_s share/"claude-memory"/"hooks.json", plugin_dir/"hooks.json"

    # Symlink binaries
    ln_s bin/"claude-memory", plugin_dir/"bin"/"claude-memory"
    ln_s bin/"claude-memory-server", plugin_dir/"bin"/"claude-memory-server"

    # Ensure memory database directory exists (but NEVER touch the database itself)
    memory_dir = Pathname.new(Dir.home) / ".claude"
    memory_dir.mkpath

    # Try to register MCP server (may fail in Homebrew sandbox - see caveats)
    server_path = plugin_dir / "bin" / "claude-memory-server"
    system "claude", "mcp", "add", "mark42", "--scope", "user", "--transport", "stdio", "--", server_path.to_s
  end

  def caveats
    <<~EOS
      Claude Memory plugin installed!

      ══════════════════════════════════════════════════════════════
      YOUR MEMORY IS SAFE
      ══════════════════════════════════════════════════════════════

      Database location: ~/.claude/memory.db

      This file contains YOUR knowledge graph and is NEVER touched by
      brew install, upgrade, or uninstall. Your memories persist forever.

      ══════════════════════════════════════════════════════════════

      Plugin location: ~/.claude/plugins/local/claude-memory/

      ══════════════════════════════════════════════════════════════
      IMPORTANT: Register the MCP server (one-time setup)
      ══════════════════════════════════════════════════════════════

      Run this command to enable the "mark42" memory server:

        claude mcp add mark42 --scope user --transport stdio -- \\
          ~/.claude/plugins/local/claude-memory/bin/claude-memory-server

      Then restart Claude Code. The hooks will fire automatically.

      ══════════════════════════════════════════════════════════════

      Available commands: /init, /status, /sync, /calibrate

      Verify installation:
        claude-memory version
        claude-memory stats

      Backup recommendation:
        cp ~/.claude/memory.db ~/.claude/memory.db.backup
    EOS
  end
end
