# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeSync < Formula
  desc "Beautiful CLI tool for syncing Claude Code configurations"
  homepage "https://github.com/mfenderov/claude-sync"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfenderov/claude-sync/releases/download/v0.2.1/claude-sync_0.2.1_darwin_amd64.tar.gz"
      sha256 "db6ee179d83091448163fcff9d87787d27dcae95164d099d3a9cbc667d0dbf07"

      def install
        bin.install "claude-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfenderov/claude-sync/releases/download/v0.2.1/claude-sync_0.2.1_darwin_arm64.tar.gz"
      sha256 "ea27a65195effab0f43b09a66427e9863fe9891f7e9e04ca9d10b0da8db5c12c"

      def install
        bin.install "claude-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/claude-sync/releases/download/v0.2.1/claude-sync_0.2.1_linux_amd64.tar.gz"
      sha256 "129b2cf41b5004f585efd27357807fc105449bd2fe2d20c0e73bb2787da89d05"
      def install
        bin.install "claude-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/claude-sync/releases/download/v0.2.1/claude-sync_0.2.1_linux_arm64.tar.gz"
      sha256 "957460993d0753f7a91fcbbc10fbd1f1eb6da70a984086d55ec1b762f5938f37"
      def install
        bin.install "claude-sync"
      end
    end
  end

  test do
    system "#{bin}/claude-sync", "--version"
  end
end
