# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark42 < Formula
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_darwin_amd64.tar.gz"
      sha256 "9e8202d0d061b35aa476b5f0d8635ac73658d6184ebf8a29e3e636c020aa6b2c"

      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_darwin_arm64.tar.gz"
      sha256 "346bda601136b7444fbf5652b1d3d4583cf4490e7d4ea977ccb1b99df4739270"

      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_linux_amd64.tar.gz"
      sha256 "6160744e18195ddaf1d3ae94f06331beee10f109c99272430a1470ff4f545be2"
      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_linux_arm64.tar.gz"
      sha256 "157b5d1a456c3e816304ca4b5500ff52258f7e05938771da595a1d0de7872c4d"
      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
  end

  def post_install
    # Create Claude Code plugin directory structure
    plugin_dir = Pathname.new(Dir.home) / ".claude" / "plugins" / "local" / "mark42"

    # Clean up existing installation (handles upgrades)
    plugin_dir.rmtree if plugin_dir.exist?
    plugin_dir.mkpath
    (plugin_dir / "bin").mkpath

    # Symlink plugin files from share directory
    ln_s share/"mark42"/".claude-plugin", plugin_dir/".claude-plugin"
    ln_s share/"mark42"/"agents", plugin_dir/"agents"
    ln_s share/"mark42"/"skills", plugin_dir/"skills"
    ln_s share/"mark42"/"commands", plugin_dir/"commands"
    ln_s share/"mark42"/"hooks", plugin_dir/"hooks"

    # Symlink binaries (use opt_bin for stable path across upgrades)
    ln_s opt_bin/"mark42", plugin_dir/"bin"/"mark42"
    ln_s opt_bin/"mark42-server", plugin_dir/"bin"/"mark42-server"

    # Ensure memory database directory exists (but NEVER touch the database itself)
    memory_dir = Pathname.new(Dir.home) / ".claude"
    memory_dir.mkpath

    # Try to register MCP server (may fail in Homebrew sandbox - see caveats)
    server_path = plugin_dir / "bin" / "mark42-server"
    system "claude", "mcp", "add", "mark42", "--scope", "user", "--transport", "stdio", "--", server_path.to_s
  end

  def caveats
    <<~EOS
      mark42 plugin installed!

      ══════════════════════════════════════════════════════════════
      YOUR MEMORY IS SAFE
      ══════════════════════════════════════════════════════════════

      Database location: ~/.claude/memory.db

      This file contains YOUR knowledge graph and is NEVER touched by
      brew install, upgrade, or uninstall. Your memories persist forever.

      ══════════════════════════════════════════════════════════════

      Plugin location: ~/.claude/plugins/local/mark42/

      ══════════════════════════════════════════════════════════════
      IMPORTANT: Register the MCP server (one-time setup)
      ══════════════════════════════════════════════════════════════

      Run this command to enable the "mark42" memory server:

        claude mcp add mark42 --scope user --transport stdio -- \\
          ~/.claude/plugins/local/mark42/bin/mark42-server

      Then restart Claude Code. The hooks will fire automatically.

      ══════════════════════════════════════════════════════════════

      Available commands: /init, /status, /sync, /calibrate

      Verify installation:
        mark42 version
        mark42 stats

      Backup recommendation:
        cp ~/.claude/memory.db ~/.claude/memory.db.backup
    EOS
  end
end
