# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark42 < Formula
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfenderov/mark42/releases/download/v2.0.0/mark42_2.0.0_darwin_amd64.tar.gz"
      sha256 "f93e4fdb4cbd50b3955a485d4da477eceb485ce398643a93ead5a080116442ab"

      def install
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
        (share/"mark42").install "hooks.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfenderov/mark42/releases/download/v2.0.0/mark42_2.0.0_darwin_arm64.tar.gz"
      sha256 "6704e6490fc7d9148484882439af1949efad5ea9f17b29b09a62b67ac5dff1be"

      def install
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
        (share/"mark42").install "hooks.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.0.0/mark42_2.0.0_linux_amd64.tar.gz"
      sha256 "0d3c95172b013feb767b22d9b59ce33e4eb6ea6b19123ec003f6354d570a7c5a"
      def install
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
        (share/"mark42").install "hooks.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.0.0/mark42_2.0.0_linux_arm64.tar.gz"
      sha256 "ec377d1a724f6433373a42bdf97e3e35b9a8eb93cccf7e3d12a8dc2c8df67e2b"
      def install
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
        (share/"mark42").install "hooks.json"
      end
    end
  end

  def post_install
    # Create Claude Code plugin directory structure
    plugin_dir = Pathname.new(Dir.home) / ".claude" / "plugins" / "local" / "mark42"

    # Clean up existing installation (handles upgrades)
    plugin_dir.rmtree if plugin_dir.exist?
    plugin_dir.mkpath
    (plugin_dir / "bin").mkpath

    # Symlink plugin files from share directory
    ln_s share/"mark42"/".claude-plugin", plugin_dir/".claude-plugin"
    ln_s share/"mark42"/"agents", plugin_dir/"agents"
    ln_s share/"mark42"/"skills", plugin_dir/"skills"
    ln_s share/"mark42"/"commands", plugin_dir/"commands"
    ln_s share/"mark42"/"hooks", plugin_dir/"hooks"
    ln_s share/"mark42"/"hooks.json", plugin_dir/"hooks.json"

    # Symlink binaries (use opt_bin for stable path across upgrades)
    ln_s opt_bin/"mark42", plugin_dir/"bin"/"mark42"
    ln_s opt_bin/"mark42-server", plugin_dir/"bin"/"mark42-server"

    # Ensure memory database directory exists (but NEVER touch the database itself)
    memory_dir = Pathname.new(Dir.home) / ".claude"
    memory_dir.mkpath

    # Try to register MCP server (may fail in Homebrew sandbox - see caveats)
    server_path = plugin_dir / "bin" / "mark42-server"
    system "claude", "mcp", "add", "mark42", "--scope", "user", "--transport", "stdio", "--", server_path.to_s
  end

  def caveats
    <<~EOS
      mark42 plugin installed!

      ══════════════════════════════════════════════════════════════
      YOUR MEMORY IS SAFE
      ══════════════════════════════════════════════════════════════

      Database location: ~/.claude/memory.db

      This file contains YOUR knowledge graph and is NEVER touched by
      brew install, upgrade, or uninstall. Your memories persist forever.

      ══════════════════════════════════════════════════════════════

      Plugin location: ~/.claude/plugins/local/mark42/

      ══════════════════════════════════════════════════════════════
      IMPORTANT: Register the MCP server (one-time setup)
      ══════════════════════════════════════════════════════════════

      Run this command to enable the "mark42" memory server:

        claude mcp add mark42 --scope user --transport stdio -- \\
          ~/.claude/plugins/local/mark42/bin/mark42-server

      Then restart Claude Code. The hooks will fire automatically.

      ══════════════════════════════════════════════════════════════

      Available commands: /init, /status, /sync, /calibrate

      Verify installation:
        mark42 version
        mark42 stats

      Backup recommendation:
        cp ~/.claude/memory.db ~/.claude/memory.db.backup
    EOS
  end
end
