# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mark42 < Formula
  desc "Local, privacy-first RAG memory system for Claude Code"
  homepage "https://github.com/mfenderov/mark42"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_darwin_amd64.tar.gz"
      sha256 "913d3d63b3302c57cb1fb94f32499ad4fc9bcbc1b897f840e19a7d5fe3326c6c"

      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_darwin_arm64.tar.gz"
      sha256 "d491ef7d89151034691293e0466c7e056da5870aadf9999a3eca4bbe13e0ca0c"

      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_linux_amd64.tar.gz"
      sha256 "1438c9eb2934aa9affb48d0ec9c8ff46c59488d66bf1ec4ff97822f90965f2ce"
      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfenderov/mark42/releases/download/v2.2.0/mark42_2.2.0_linux_arm64.tar.gz"
      sha256 "60c2b461a12cc075021f536d927238ac9d7ef5b58ca27ed84088735a3f9a40f6"
      define_method(:install) do
        bin.install "mark42"
        bin.install "mark42-server"

        # Install plugin assets to share directory (Homebrew-managed)
        (share/"mark42").install ".claude-plugin"
        (share/"mark42").install "agents"
        (share/"mark42").install "skills"
        (share/"mark42").install "commands"
        (share/"mark42").install "hooks"
      end
    end
  end

  def post_install
    # Create Claude Code plugin directory structure
    plugin_dir = Pathname.new(Dir.home) / ".claude" / "plugins" / "local" / "mark42"

    # Clean up existing installation (handles upgrades)
    plugin_dir.rmtree if plugin_dir.exist?
    plugin_dir.mkpath
    (plugin_dir / "bin").mkpath

    # Symlink plugin files from share directory
    ln_s share/"mark42"/".claude-plugin", plugin_dir/".claude-plugin"
    ln_s share/"mark42"/"agents", plugin_dir/"agents"
    ln_s share/"mark42"/"skills", plugin_dir/"skills"
    ln_s share/"mark42"/"commands", plugin_dir/"commands"
    ln_s share/"mark42"/"hooks", plugin_dir/"hooks"

    # Symlink binaries (use opt_bin for stable path across upgrades)
    ln_s opt_bin/"mark42", plugin_dir/"bin"/"mark42"
    ln_s opt_bin/"mark42-server", plugin_dir/"bin"/"mark42-server"

    # Ensure memory database directory exists (but NEVER touch the database itself)
    memory_dir = Pathname.new(Dir.home) / ".claude"
    memory_dir.mkpath

    # Try to register MCP server (may fail in Homebrew sandbox - see caveats)
    server_path = plugin_dir / "bin" / "mark42-server"
    system "claude", "mcp", "add", "mark42", "--scope", "user", "--transport", "stdio", "--", server_path.to_s
  end

  def caveats
    <<~EOS
      mark42 plugin installed!

      ══════════════════════════════════════════════════════════════
      YOUR MEMORY IS SAFE
      ══════════════════════════════════════════════════════════════

      Database location: ~/.claude/memory.db

      This file contains YOUR knowledge graph and is NEVER touched by
      brew install, upgrade, or uninstall. Your memories persist forever.

      ══════════════════════════════════════════════════════════════

      Plugin location: ~/.claude/plugins/local/mark42/

      ══════════════════════════════════════════════════════════════
      IMPORTANT: Register the MCP server (one-time setup)
      ══════════════════════════════════════════════════════════════

      Run this command to enable the "mark42" memory server:

        claude mcp add mark42 --scope user --transport stdio -- \\
          ~/.claude/plugins/local/mark42/bin/mark42-server

      Then restart Claude Code. The hooks will fire automatically.

      ══════════════════════════════════════════════════════════════

      Available commands: /init, /status, /sync, /calibrate

      Verify installation:
        mark42 version
        mark42 stats

      Backup recommendation:
        cp ~/.claude/memory.db ~/.claude/memory.db.backup
    EOS
  end
end
